---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - secrets
  verbs:
  - create
  - delete
  - list
  - patch
  - update
- apiGroups:
  - stackit.cloud
  resources:
  - postgresflexes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stackit.cloud
  resources:
  - postgresflexes/finalizers
  verbs:
  - update
- apiGroups:
  - stackit.cloud
  resources:
  - postgresflexes/status
  verbs:
  - get
  - patch
  - update
